<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['abbr_2' => 'AF', 'abbr_3' => 'AFG', 'code' => '93',       'name' => 'Afghanistan'],
            ['abbr_2' => 'AL', 'abbr_3' => 'ALB', 'code' => '355',      'name' => 'Albania'],
            ['abbr_2' => 'DZ', 'abbr_3' => 'DZA', 'code' => '213',      'name' => 'Algeria'],
            ['abbr_2' => 'AS', 'abbr_3' => 'ASM', 'code' => '1',        'name' => 'American Samoa'],
            ['abbr_2' => 'AD', 'abbr_3' => 'AND', 'code' => '376',      'name' => 'Andorra'],
            ['abbr_2' => 'AO', 'abbr_3' => 'AGO', 'code' => '244',      'name' => 'Angola'],
            ['abbr_2' => 'AI', 'abbr_3' => 'AIA', 'code' => '1-264',    'name' => 'Anguilla'],
            ['abbr_2' => 'AQ', 'abbr_3' => 'ATA', 'code' => '672',      'name' => 'Antarctica'],
            ['abbr_2' => 'AG', 'abbr_3' => 'ATG', 'code' => '1-268',    'name' => 'Antigua and Barbuda'],
            ['abbr_2' => 'AR', 'abbr_3' => 'ARG', 'code' => '54',       'name' => 'Argentina'],
            ['abbr_2' => 'AM', 'abbr_3' => 'ARM', 'code' => '374',      'name' => 'Armenia'],
            ['abbr_2' => 'AW', 'abbr_3' => 'ABW', 'code' => '297',      'name' => 'Aruba'],
            ['abbr_2' => 'AU', 'abbr_3' => 'AUS', 'code' => '61',       'name' => 'Australia'],
            ['abbr_2' => 'AT', 'abbr_3' => 'AUT', 'code' => '43',       'name' => 'Austria'],
            ['abbr_2' => 'AZ', 'abbr_3' => 'AZE', 'code' => '994',      'name' => 'Azerbaijan'],
            ['abbr_2' => 'BS', 'abbr_3' => 'BHS', 'code' => '1-242',    'name' => 'Bahamas'],
            ['abbr_2' => 'BH', 'abbr_3' => 'BHR', 'code' => '973',      'name' => 'Bahrain'],
            ['abbr_2' => 'BD', 'abbr_3' => 'BGD', 'code' => '880',      'name' => 'Bangladesh'],
            ['abbr_2' => 'BB', 'abbr_3' => 'BRB', 'code' => '1-246',    'name' => 'Barbados'],
            ['abbr_2' => 'BY', 'abbr_3' => 'BLR', 'code' => '375',      'name' => 'Belarus'],
            ['abbr_2' => 'BE', 'abbr_3' => 'BEL', 'code' => '32',       'name' => 'Belgium'],
            ['abbr_2' => 'BZ', 'abbr_3' => 'BLZ', 'code' => '501',      'name' => 'Belize'],
            ['abbr_2' => 'BJ', 'abbr_3' => 'BEN', 'code' => '229',      'name' => 'Benin'],
            ['abbr_2' => 'BM', 'abbr_3' => 'BMU', 'code' => '1-441',    'name' => 'Bermuda'],
            ['abbr_2' => 'BT', 'abbr_3' => 'BTN', 'code' => '975',      'name' => 'Bhutan'],
            ['abbr_2' => 'BO', 'abbr_3' => 'BOL', 'code' => '591',      'name' => 'Bolivia'],
            ['abbr_2' => 'BQ', 'abbr_3' => 'BES', 'code' => '599',      'name' => 'Bonaire, Sint Eustatius, and Saba'],
            ['abbr_2' => 'BA', 'abbr_3' => 'BIH', 'code' => '387',      'name' => 'Bosnia and Herzegovina'],
            ['abbr_2' => 'BW', 'abbr_3' => 'BWA', 'code' => '267',      'name' => 'Botswana'],
            ['abbr_2' => 'BR', 'abbr_3' => 'BRA', 'code' => '55',       'name' => 'Brazil'],
            ['abbr_2' => 'IO', 'abbr_3' => 'IOT', 'code' => '246',      'name' => 'British Indian Ocean Territory'],
            ['abbr_2' => 'VG', 'abbr_3' => 'VGB', 'code' => '1-284',    'name' => 'British Virgin Islands'],
            ['abbr_2' => 'BN', 'abbr_3' => 'BRN', 'code' => '673',      'name' => 'Brunei'],
            ['abbr_2' => 'BG', 'abbr_3' => 'BGR', 'code' => '359',      'name' => 'Bulgaria'],
            ['abbr_2' => 'BF', 'abbr_3' => 'BFA', 'code' => '226',      'name' => 'Burkina Faso'],
            ['abbr_2' => 'BI', 'abbr_3' => 'BDI', 'code' => '257',      'name' => 'Burundi'],
            ['abbr_2' => 'KH', 'abbr_3' => 'KHM', 'code' => '855',      'name' => 'Cambodia'],
            ['abbr_2' => 'CM', 'abbr_3' => 'CMR', 'code' => '237',      'name' => 'Cameroon'],
            ['abbr_2' => 'CA', 'abbr_3' => 'CAN', 'code' => '1',        'name' => 'Canada'],
            ['abbr_2' => 'CV', 'abbr_3' => 'CPV', 'code' => '238',      'name' => 'Cape Verde'],
            ['abbr_2' => 'KY', 'abbr_3' => 'CYM', 'code' => '1-345',    'name' => 'Cayman Islands'],
            ['abbr_2' => 'CF', 'abbr_3' => 'CAF', 'code' => '236',      'name' => 'Central African Republic'],
            ['abbr_2' => 'TD', 'abbr_3' => 'TCD', 'code' => '235',      'name' => 'Chad'],
            ['abbr_2' => 'CL', 'abbr_3' => 'CHL', 'code' => '56',       'name' => 'Chile'],
            ['abbr_2' => 'CN', 'abbr_3' => 'CHN', 'code' => '86',       'name' => 'China'],
            ['abbr_2' => 'CX', 'abbr_3' => 'CXR', 'code' => '61',       'name' => 'Christmas Island'],
            ['abbr_2' => 'CC', 'abbr_3' => 'CCK', 'code' => '61',       'name' => 'Cocos Islands'],
            ['abbr_2' => 'CO', 'abbr_3' => 'COL', 'code' => '57',       'name' => 'Colombia'],
            ['abbr_2' => 'KM', 'abbr_3' => 'COM', 'code' => '269',      'name' => 'Comoros'],
            ['abbr_2' => 'CK', 'abbr_3' => 'COK', 'code' => '682',      'name' => 'Cook Islands'],
            ['abbr_2' => 'CR', 'abbr_3' => 'CRI', 'code' => '506',      'name' => 'Costa Rica'],
            ['abbr_2' => 'HR', 'abbr_3' => 'HRV', 'code' => '385',      'name' => 'Croatia'],
            ['abbr_2' => 'CU', 'abbr_3' => 'CUB', 'code' => '53',       'name' => 'Cuba'],
            ['abbr_2' => 'CW', 'abbr_3' => 'CUW', 'code' => '599',      'name' => 'Curaçao'],
            ['abbr_2' => 'CY', 'abbr_3' => 'CYP', 'code' => '357',      'name' => 'Cyprus'],
            ['abbr_2' => 'CZ', 'abbr_3' => 'CZE', 'code' => '420',      'name' => 'Czech Republic'],
            ['abbr_2' => 'CD', 'abbr_3' => 'COD', 'code' => '243',      'name' => 'Democratic Republic of the Congo'],
            ['abbr_2' => 'DK', 'abbr_3' => 'DNK', 'code' => '45',       'name' => 'Denmark'],
            ['abbr_2' => 'DJ', 'abbr_3' => 'DJI', 'code' => '253',      'name' => 'Djibouti'],
            ['abbr_2' => 'DM', 'abbr_3' => 'DMA', 'code' => '1-767',    'name' => 'Dominica'],
            ['abbr_2' => 'DO', 'abbr_3' => 'DOM', 'code' => '1-809',    'name' => 'Dominican Republic'],
            ['abbr_2' => 'TL', 'abbr_3' => 'TLS', 'code' => '670',      'name' => 'East Timor'],
            ['abbr_2' => 'EC', 'abbr_3' => 'ECU', 'code' => '593',      'name' => 'Ecuador'],
            ['abbr_2' => 'EG', 'abbr_3' => 'EGY', 'code' => '20',       'name' => 'Egypt'],
            ['abbr_2' => 'SV', 'abbr_3' => 'SLV', 'code' => '503',      'name' => 'El Salvador'],
            ['abbr_2' => 'GQ', 'abbr_3' => 'GNQ', 'code' => '240',      'name' => 'Equatorial Guinea'],
            ['abbr_2' => 'ER', 'abbr_3' => 'ERI', 'code' => '291',      'name' => 'Eritrea'],
            ['abbr_2' => 'EE', 'abbr_3' => 'EST', 'code' => '372',      'name' => 'Estonia'],
            ['abbr_2' => 'ET', 'abbr_3' => 'ETH', 'code' => '251',      'name' => 'Ethiopia'],
            ['abbr_2' => 'FK', 'abbr_3' => 'FLK', 'code' => '500',      'name' => 'Falkland Islands'],
            ['abbr_2' => 'FO', 'abbr_3' => 'FRO', 'code' => '298',      'name' => 'Faroe Islands'],
            ['abbr_2' => 'FJ', 'abbr_3' => 'FJI', 'code' => '679',      'name' => 'Fiji'],
            ['abbr_2' => 'FI', 'abbr_3' => 'FIN', 'code' => '358',      'name' => 'Finland'],
            ['abbr_2' => 'FR', 'abbr_3' => 'FRA', 'code' => '33',       'name' => 'France'],
            ['abbr_2' => 'GF', 'abbr_3' => 'GUF', 'code' => '594',      'name' => 'French Guiana'],
            ['abbr_2' => 'PF', 'abbr_3' => 'PYF', 'code' => '689',      'name' => 'French Polynesia'],
            ['abbr_2' => 'GA', 'abbr_3' => 'GAB', 'code' => '241',      'name' => 'Gabon'],
            ['abbr_2' => 'GM', 'abbr_3' => 'GMB', 'code' => '220',      'name' => 'Gambia'],
            ['abbr_2' => 'GE', 'abbr_3' => 'GEO', 'code' => '995',      'name' => 'Georgia'],
            ['abbr_2' => 'DE', 'abbr_3' => 'DEU', 'code' => '49',       'name' => 'Germany'],
            ['abbr_2' => 'GH', 'abbr_3' => 'GHA', 'code' => '233',      'name' => 'Ghana'],
            ['abbr_2' => 'GI', 'abbr_3' => 'GIB', 'code' => '350',      'name' => 'Gibraltar'],
            ['abbr_2' => 'GR', 'abbr_3' => 'GRC', 'code' => '30',       'name' => 'Greece'],
            ['abbr_2' => 'GL', 'abbr_3' => 'GRL', 'code' => '299',      'name' => 'Greenland'],
            ['abbr_2' => 'GD', 'abbr_3' => 'GRD', 'code' => '1-473',    'name' => 'Grenada'],
            ['abbr_2' => 'GP', 'abbr_3' => 'GLP', 'code' => '590',      'name' => 'Guadeloupe'],
            ['abbr_2' => 'GU', 'abbr_3' => 'GUM', 'code' => '1-671',    'name' => 'Guam'],
            ['abbr_2' => 'GT', 'abbr_3' => 'GTM', 'code' => '502',      'name' => 'Guatemala'],
            ['abbr_2' => 'GG', 'abbr_3' => 'GGY', 'code' => '44',       'name' => 'Guernsey'],
            ['abbr_2' => 'GN', 'abbr_3' => 'GIN', 'code' => '224',      'name' => 'Guinea'],
            ['abbr_2' => 'GW', 'abbr_3' => 'GNB', 'code' => '245',      'name' => 'Guinea-Bissau'],
            ['abbr_2' => 'GY', 'abbr_3' => 'GUY', 'code' => '592',      'name' => 'Guyana'],
            ['abbr_2' => 'HT', 'abbr_3' => 'HTI', 'code' => '509',      'name' => 'Haiti'],
            ['abbr_2' => 'HN', 'abbr_3' => 'HND', 'code' => '504',      'name' => 'Honduras'],
            ['abbr_2' => 'HK', 'abbr_3' => 'HKG', 'code' => '852',      'name' => 'Hong Kong'],
            ['abbr_2' => 'HU', 'abbr_3' => 'HUN', 'code' => '36',       'name' => 'Hungary'],
            ['abbr_2' => 'IS', 'abbr_3' => 'ISL', 'code' => '354',      'name' => 'Iceland'],
            ['abbr_2' => 'IN', 'abbr_3' => 'IND', 'code' => '91',       'name' => 'India'],
            ['abbr_2' => 'ID', 'abbr_3' => 'IDN', 'code' => '62',       'name' => 'Indonesia'],
            ['abbr_2' => 'IR', 'abbr_3' => 'IRN', 'code' => '98',       'name' => 'Iran'],
            ['abbr_2' => 'IQ', 'abbr_3' => 'IRQ', 'code' => '964',      'name' => 'Iraq'],
            ['abbr_2' => 'IE', 'abbr_3' => 'IRL', 'code' => '353',      'name' => 'Ireland'],
            ['abbr_2' => 'IM', 'abbr_3' => 'IMN', 'code' => '44',       'name' => 'Isle of Man'],
            ['abbr_2' => 'IL', 'abbr_3' => 'ISR', 'code' => '972',      'name' => 'Israel'],
            ['abbr_2' => 'IT', 'abbr_3' => 'ITA', 'code' => '39',       'name' => 'Italy'],
            ['abbr_2' => 'CI', 'abbr_3' => 'CIV', 'code' => '225',      'name' => 'Ivory Coast'],
            ['abbr_2' => 'JM', 'abbr_3' => 'JAM', 'code' => '1-876',    'name' => 'Jamaica'],
            ['abbr_2' => 'JP', 'abbr_3' => 'JPN', 'code' => '81',       'name' => 'Japan'],
            ['abbr_2' => 'JE', 'abbr_3' => 'JEY', 'code' => '44',       'name' => 'Jersey'],
            ['abbr_2' => 'JO', 'abbr_3' => 'JOR', 'code' => '962',      'name' => 'Jordan'],
            ['abbr_2' => 'KZ', 'abbr_3' => 'KAZ', 'code' => '7',        'name' => 'Kazakhstan'],
            ['abbr_2' => 'KE', 'abbr_3' => 'KEN', 'code' => '254',      'name' => 'Kenya'],
            ['abbr_2' => 'KI', 'abbr_3' => 'KIR', 'code' => '686',      'name' => 'Kiribati'],
            ['abbr_2' => 'XK', 'abbr_3' => 'XKX', 'code' => '383',      'name' => 'Kosovo'],
            ['abbr_2' => 'KW', 'abbr_3' => 'KWT', 'code' => '965',      'name' => 'Kuwait'],
            ['abbr_2' => 'KG', 'abbr_3' => 'KGZ', 'code' => '996',      'name' => 'Kyrgyzstan'],
            ['abbr_2' => 'LA', 'abbr_3' => 'LAO', 'code' => '856',      'name' => 'Laos'],
            ['abbr_2' => 'LV', 'abbr_3' => 'LVA', 'code' => '371',      'name' => 'Latvia'],
            ['abbr_2' => 'LB', 'abbr_3' => 'LBN', 'code' => '961',      'name' => 'Lebanon'],
            ['abbr_2' => 'LS', 'abbr_3' => 'LSO', 'code' => '266',      'name' => 'Lesotho'],
            ['abbr_2' => 'LR', 'abbr_3' => 'LBR', 'code' => '231',      'name' => 'Liberia'],
            ['abbr_2' => 'LY', 'abbr_3' => 'LBY', 'code' => '218',      'name' => 'Libya'],
            ['abbr_2' => 'LI', 'abbr_3' => 'LIE', 'code' => '423',      'name' => 'Liechtenstein'],
            ['abbr_2' => 'LT', 'abbr_3' => 'LTU', 'code' => '370',      'name' => 'Lithuania'],
            ['abbr_2' => 'LU', 'abbr_3' => 'LUX', 'code' => '352',      'name' => 'Luxembourg'],
            ['abbr_2' => 'MO', 'abbr_3' => 'MAC', 'code' => '853',      'name' => 'Macau'],
            ['abbr_2' => 'MK', 'abbr_3' => 'MKD', 'code' => '389',      'name' => 'North Macedonia'],
            ['abbr_2' => 'MG', 'abbr_3' => 'MDG', 'code' => '261',      'name' => 'Madagascar'],
            ['abbr_2' => 'MW', 'abbr_3' => 'MWI', 'code' => '265',      'name' => 'Malawi'],
            ['abbr_2' => 'MY', 'abbr_3' => 'MYS', 'code' => '60',       'name' => 'Malaysia'],
            ['abbr_2' => 'MV', 'abbr_3' => 'MDV', 'code' => '960',      'name' => 'Maldives'],
            ['abbr_2' => 'ML', 'abbr_3' => 'MLI', 'code' => '223',      'name' => 'Mali'],
            ['abbr_2' => 'MT', 'abbr_3' => 'MLT', 'code' => '356',      'name' => 'Malta'],
            ['abbr_2' => 'MH', 'abbr_3' => 'MHL', 'code' => '692',      'name' => 'Marshall Islands'],
            ['abbr_2' => 'MQ', 'abbr_3' => 'MTQ', 'code' => '596',      'name' => 'Martinique'],
            ['abbr_2' => 'MR', 'abbr_3' => 'MRT', 'code' => '222',      'name' => 'Mauritania'],
            ['abbr_2' => 'MU', 'abbr_3' => 'MUS', 'code' => '230',      'name' => 'Mauritius'],
            ['abbr_2' => 'YT', 'abbr_3' => 'MYT', 'code' => '262',      'name' => 'Mayotte'],
            ['abbr_2' => 'MX', 'abbr_3' => 'MEX', 'code' => '52',       'name' => 'Mexico'],
            ['abbr_2' => 'FM', 'abbr_3' => 'FSM', 'code' => '691',      'name' => 'Micronesia'],
            ['abbr_2' => 'MD', 'abbr_3' => 'MDA', 'code' => '373',      'name' => 'Moldova'],
            ['abbr_2' => 'MC', 'abbr_3' => 'MCO', 'code' => '377',      'name' => 'Monaco'],
            ['abbr_2' => 'MN', 'abbr_3' => 'MNG', 'code' => '976',      'name' => 'Mongolia'],
            ['abbr_2' => 'ME', 'abbr_3' => 'MNE', 'code' => '382',      'name' => 'Montenegro'],
            ['abbr_2' => 'MS', 'abbr_3' => 'MSR', 'code' => '1-664',    'name' => 'Montserrat'],
            ['abbr_2' => 'MA', 'abbr_3' => 'MAR', 'code' => '212',      'name' => 'Morocco'],
            ['abbr_2' => 'MZ', 'abbr_3' => 'MOZ', 'code' => '258',      'name' => 'Mozambique'],
            ['abbr_2' => 'MM', 'abbr_3' => 'MMR', 'code' => '95',       'name' => 'Myanmar'],
            ['abbr_2' => 'NA', 'abbr_3' => 'NAM', 'code' => '264',      'name' => 'Namibia'],
            ['abbr_2' => 'NR', 'abbr_3' => 'NRU', 'code' => '674',      'name' => 'Nauru'],
            ['abbr_2' => 'NP', 'abbr_3' => 'NPL', 'code' => '977',      'name' => 'Nepal'],
            ['abbr_2' => 'NL', 'abbr_3' => 'NLD', 'code' => '31',       'name' => 'Netherlands'],
            ['abbr_2' => 'NC', 'abbr_3' => 'NCL', 'code' => '687',      'name' => 'New Caledonia'],
            ['abbr_2' => 'NZ', 'abbr_3' => 'NZL', 'code' => '64',       'name' => 'New Zealand'],
            ['abbr_2' => 'NI', 'abbr_3' => 'NIC', 'code' => '505',      'name' => 'Nicaragua'],
            ['abbr_2' => 'NE', 'abbr_3' => 'NER', 'code' => '227',      'name' => 'Niger'],
            ['abbr_2' => 'NG', 'abbr_3' => 'NGA', 'code' => '234',      'name' => 'Nigeria'],
            ['abbr_2' => 'NU', 'abbr_3' => 'NIU', 'code' => '683',      'name' => 'Niue'],
            ['abbr_2' => 'NF', 'abbr_3' => 'NFK', 'code' => '672',      'name' => 'Norfolk Island'],
            ['abbr_2' => 'KP', 'abbr_3' => 'PRK', 'code' => '850',      'name' => 'North Korea'],
            ['abbr_2' => 'MP', 'abbr_3' => 'MNP', 'code' => '1-670',    'name' => 'Northern Mariana Islands'],
            ['abbr_2' => 'NO', 'abbr_3' => 'NOR', 'code' => '47',       'name' => 'Norway'],
            ['abbr_2' => 'OM', 'abbr_3' => 'OMN', 'code' => '968',      'name' => 'Oman'],
            ['abbr_2' => 'PK', 'abbr_3' => 'PAK', 'code' => '92',       'name' => 'Pakistan'],
            ['abbr_2' => 'PW', 'abbr_3' => 'PLW', 'code' => '680',      'name' => 'Palau'],
            ['abbr_2' => 'PS', 'abbr_3' => 'PSE', 'code' => '970',      'name' => 'Palestine'],
            ['abbr_2' => 'PA', 'abbr_3' => 'PAN', 'code' => '507',      'name' => 'Panama'],
            ['abbr_2' => 'PG', 'abbr_3' => 'PNG', 'code' => '675',      'name' => 'Papua New Guinea'],
            ['abbr_2' => 'PY', 'abbr_3' => 'PRY', 'code' => '595',      'name' => 'Paraguay'],
            ['abbr_2' => 'PE', 'abbr_3' => 'PER', 'code' => '51',       'name' => 'Peru'],
            ['abbr_2' => 'PH', 'abbr_3' => 'PHL', 'code' => '63',       'name' => 'Philippines'],
            ['abbr_2' => 'PN', 'abbr_3' => 'PCN', 'code' => '870',      'name' => 'Pitcairn Islands'],
            ['abbr_2' => 'PL', 'abbr_3' => 'POL', 'code' => '48',       'name' => 'Poland'],
            ['abbr_2' => 'PT', 'abbr_3' => 'PRT', 'code' => '351',      'name' => 'Portugal'],
            ['abbr_2' => 'PR', 'abbr_3' => 'PRI', 'code' => '1-787',    'name' => 'Puerto Rico'],
            ['abbr_2' => 'QA', 'abbr_3' => 'QAT', 'code' => '974',      'name' => 'Qatar'],
            ['abbr_2' => 'CG', 'abbr_3' => 'COG', 'code' => '242',      'name' => 'Republic of the Congo'],
            ['abbr_2' => 'RE', 'abbr_3' => 'REU', 'code' => '262',      'name' => 'Reunion'],
            ['abbr_2' => 'RO', 'abbr_3' => 'ROU', 'code' => '40',       'name' => 'Romania'],
            ['abbr_2' => 'RU', 'abbr_3' => 'RUS', 'code' => '7',        'name' => 'Russia'],
            ['abbr_2' => 'RW', 'abbr_3' => 'RWA', 'code' => '250',      'name' => 'Rwanda'],
            ['abbr_2' => 'BL', 'abbr_3' => 'BLM', 'code' => '590',      'name' => 'Saint Barthelemy'],
            ['abbr_2' => 'SH', 'abbr_3' => 'SHN', 'code' => '290',      'name' => 'Saint Helena'],
            ['abbr_2' => 'KN', 'abbr_3' => 'KNA', 'code' => '1-869',    'name' => 'Saint Kitts and Nevis'],
            ['abbr_2' => 'LC', 'abbr_3' => 'LCA', 'code' => '1-758',    'name' => 'Saint Lucia'],
            ['abbr_2' => 'MF', 'abbr_3' => 'MAF', 'code' => '590',      'name' => 'Saint Martin'],
            ['abbr_2' => 'PM', 'abbr_3' => 'SPM', 'code' => '508',      'name' => 'Saint Pierre and Miquelon'],
            ['abbr_2' => 'VC', 'abbr_3' => 'VCT', 'code' => '1-784',    'name' => 'Saint Vincent and the Grenadines'],
            ['abbr_2' => 'WS', 'abbr_3' => 'WSM', 'code' => '685',      'name' => 'Samoa'],
            ['abbr_2' => 'SM', 'abbr_3' => 'SMR', 'code' => '378',      'name' => 'San Marino'],
            ['abbr_2' => 'ST', 'abbr_3' => 'STP', 'code' => '239',      'name' => 'Sao Tome and Principe'],
            ['abbr_2' => 'SA', 'abbr_3' => 'SAU', 'code' => '966',      'name' => 'Saudi Arabia'],
            ['abbr_2' => 'SN', 'abbr_3' => 'SEN', 'code' => '221',      'name' => 'Senegal'],
            ['abbr_2' => 'RS', 'abbr_3' => 'SRB', 'code' => '381',      'name' => 'Serbia'],
            ['abbr_2' => 'SC', 'abbr_3' => 'SYC', 'code' => '248',      'name' => 'Seychelles'],
            ['abbr_2' => 'SL', 'abbr_3' => 'SLE', 'code' => '232',      'name' => 'Sierra Leone'],
            ['abbr_2' => 'SG', 'abbr_3' => 'SGP', 'code' => '65',       'name' => 'Singapore'],
            ['abbr_2' => 'SX', 'abbr_3' => 'SXM', 'code' => '1-721',    'name' => 'Sint Maarten'],
            ['abbr_2' => 'SK', 'abbr_3' => 'SVK', 'code' => '421',      'name' => 'Slovakia'],
            ['abbr_2' => 'SI', 'abbr_3' => 'SVN', 'code' => '386',      'name' => 'Slovenia'],
            ['abbr_2' => 'SB', 'abbr_3' => 'SLB', 'code' => '677',      'name' => 'Solomon Islands'],
            ['abbr_2' => 'SO', 'abbr_3' => 'SOM', 'code' => '252',      'name' => 'Somalia'],
            ['abbr_2' => 'ZA', 'abbr_3' => 'ZAF', 'code' => '27',       'name' => 'South Africa'],
            ['abbr_2' => 'KR', 'abbr_3' => 'KOR', 'code' => '82',       'name' => 'South Korea'],
            ['abbr_2' => 'SS', 'abbr_3' => 'SSD', 'code' => '211',      'name' => 'South Sudan'],
            ['abbr_2' => 'ES', 'abbr_3' => 'ESP', 'code' => '34',       'name' => 'Spain'],
            ['abbr_2' => 'LK', 'abbr_3' => 'LKA', 'code' => '94',       'name' => 'Sri Lanka'],
            ['abbr_2' => 'SD', 'abbr_3' => 'SDN', 'code' => '249',      'name' => 'Sudan'],
            ['abbr_2' => 'SR', 'abbr_3' => 'SUR', 'code' => '597',      'name' => 'Suriname'],
            ['abbr_2' => 'SJ', 'abbr_3' => 'SJM', 'code' => '47',       'name' => 'Svalbard and Jan Mayen'],
            ['abbr_2' => 'SZ', 'abbr_3' => 'SWZ', 'code' => '268',      'name' => 'Eswatini'],
            ['abbr_2' => 'SE', 'abbr_3' => 'SWE', 'code' => '46',       'name' => 'Sweden'],
            ['abbr_2' => 'CH', 'abbr_3' => 'CHE', 'code' => '41',       'name' => 'Switzerland'],
            ['abbr_2' => 'SY', 'abbr_3' => 'SYR', 'code' => '963',      'name' => 'Syria'],
            ['abbr_2' => 'TW', 'abbr_3' => 'TWN', 'code' => '886',      'name' => 'Taiwan'],
            ['abbr_2' => 'TJ', 'abbr_3' => 'TJK', 'code' => '992',      'name' => 'Tajikistan'],
            ['abbr_2' => 'TZ', 'abbr_3' => 'TZA', 'code' => '255',      'name' => 'Tanzania'],
            ['abbr_2' => 'TH', 'abbr_3' => 'THA', 'code' => '66',       'name' => 'Thailand'],
            ['abbr_2' => 'TG', 'abbr_3' => 'TGO', 'code' => '228',      'name' => 'Togo'],
            ['abbr_2' => 'TK', 'abbr_3' => 'TKL', 'code' => '690',      'name' => 'Tokelau'],
            ['abbr_2' => 'TO', 'abbr_3' => 'TON', 'code' => '676',      'name' => 'Tonga'],
            ['abbr_2' => 'TT', 'abbr_3' => 'TTO', 'code' => '1-868',    'name' => 'Trinidad and Tobago'],
            ['abbr_2' => 'TN', 'abbr_3' => 'TUN', 'code' => '216',      'name' => 'Tunisia'],
            ['abbr_2' => 'TR', 'abbr_3' => 'TUR', 'code' => '90',       'name' => 'Turkey'],
            ['abbr_2' => 'TM', 'abbr_3' => 'TKM', 'code' => '993',      'name' => 'Turkmenistan'],
            ['abbr_2' => 'TC', 'abbr_3' => 'TCA', 'code' => '1-649',    'name' => 'Turks and Caicos Islands'],
            ['abbr_2' => 'TV', 'abbr_3' => 'TUV', 'code' => '688',      'name' => 'Tuvalu'],
            ['abbr_2' => 'UG', 'abbr_3' => 'UGA', 'code' => '256',      'name' => 'Uganda'],
            ['abbr_2' => 'UA', 'abbr_3' => 'UKR', 'code' => '380',      'name' => 'Ukraine'],
            ['abbr_2' => 'AE', 'abbr_3' => 'ARE', 'code' => '971',      'name' => 'United Arab Emirates'],
            ['abbr_2' => 'GB', 'abbr_3' => 'GBR', 'code' => '44',       'name' => 'United Kingdom'],
            ['abbr_2' => 'US', 'abbr_3' => 'USA', 'code' => '1',        'name' => 'United States'],
            ['abbr_2' => 'UY', 'abbr_3' => 'URY', 'code' => '598',      'name' => 'Uruguay'],
            ['abbr_2' => 'UZ', 'abbr_3' => 'UZB', 'code' => '998',      'name' => 'Uzbekistan'],
            ['abbr_2' => 'VU', 'abbr_3' => 'VUT', 'code' => '678',      'name' => 'Vanuatu'],
            ['abbr_2' => 'VA', 'abbr_3' => 'VAT', 'code' => '379',      'name' => 'Vatican City'],
            ['abbr_2' => 'VE', 'abbr_3' => 'VEN', 'code' => '58',       'name' => 'Venezuela'],
            ['abbr_2' => 'VN', 'abbr_3' => 'VNM', 'code' => '84',       'name' => 'Vietnam'],
            ['abbr_2' => 'WF', 'abbr_3' => 'WLF', 'code' => '681',      'name' => 'Wallis and Futuna'],
            ['abbr_2' => 'EH', 'abbr_3' => 'ESH', 'code' => '212',      'name' => 'Western Sahara'],
            ['abbr_2' => 'YE', 'abbr_3' => 'YEM', 'code' => '967',      'name' => 'Yemen'],
            ['abbr_2' => 'ZM', 'abbr_3' => 'ZMB', 'code' => '260',      'name' => 'Zambia'],
            ['abbr_2' => 'ZW', 'abbr_3' => 'ZWE', 'code' => '263',      'name' => 'Zimbabwe']
        ];
        
        DB::table('countries')->insert($countries);
    }
}
